# Generated by Django 2.1.2 on 2018-10-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('when', models.DateField()),
                ('associates', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('agents', models.TextField()),
                ('members', models.TextField()),
                ('files', models.TextField()),
                ('mls_id', models.CharField(max_length=255)),
                ('completed', models.IntegerField()),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mls', models.CharField(db_column='MLS', max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('deleted', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'open_houses',
                'managed': False,
            },
        ),
    ]
