# Generated by Django 2.1.2 on 2018-11-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhouse',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
