# Generated by Django 2.1.3 on 2018-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openhouses', '0002_auto_20181109_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhouse',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='openhouses/brochures'),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='openhouses/images'),
        ),
    ]
