# Generated by Django 2.1.2 on 2018-10-16 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('state', models.CharField(default='New', max_length=64)),
                ('phone_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_home', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_work', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_times', models.CharField(blank=True, max_length=255, null=True)),
                ('email_personal', models.CharField(blank=True, max_length=255, null=True)),
                ('email_work', models.CharField(blank=True, max_length=255, null=True)),
                ('workplace', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('field_changed', models.CharField(blank=True, max_length=255, null=True)),
                ('value_before', models.TextField(blank=True, null=True)),
                ('value_after', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='contacts.Contact')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
