# Generated by Django 2.1.2 on 2018-10-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhouses', '0001_initial'),
        ('contacts', '0002_auto_20181017_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='workplace',
            new_name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='agent_company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='agent_email',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='agent_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mortgage_broker',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mortgage_company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='mortgage_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='open_house_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openhouses.OpenHouse'),
        ),
    ]
