# Generated by Django 2.1.3 on 2018-11-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='import_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
