# Generated by Django 2.1.3 on 2018-12-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20181130_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(related_name='tag_set', to='contacts.Contact')),
            ],
        ),
    ]
